### ISSUE TITLE
escape key doesn't go back

### ISSUE THREAD

**Issue by glitch128** [githubcoderelatedstufflol/Nougat#1]
whenever I go into an app, I can't get back to the home screen because the navbar is hidden, and the escape key does not go back.

**Comment by githubcoderelatedstufflol** [comment]
Sorry for the late response!
It seems this is a bug with Browserling and not the library, and unless you ask Browserling to fix it (which they probably won't) I can't fix it. If the navbar is hidden and escape key doesn't work, the only way to fix it is to re-launch the OS.
